"""
Crypto AI Bot
Analysis Weights System (with Warning Severity)
"""

REASON_WEIGHTS = {
    "Market Structure Bullish": 5,
    "BOS Bullish Break": 5,
    "MTF Strong Bullish": 5,
    "Real Breakout": 5,
    "Trending Market": 4,
    "EMA20 > EMA50": 4,
    "EMA50 > EMA200": 4,
    "High Volume": 4,
    "Bullish Order Block": 4,
    "RSI Bullish Divergence": 4,
    "MACD Bullish Divergence": 4,
    "+DI > -DI": 3,
    "Healthy RSI": 3,
    "Volume Breakout": 3,
    "Price Above VWAP": 3,
    "Discount Zone": 3,
    "Buy Side Liquidity Sweep": 3,
    "Bullish Trendline Break": 3,
    "Strong Support": 3,
    "OI Long Build Up": 3,
    "MTF Bullish": 3,
    "Funding Bullish Bias": 2,
    "Unfilled Bullish FVG": 2,
    "Near POC": 2,
    "EMA Slopes Positive": 2,
    "Bullish Candlestick": 2,
    "Price in Golden Zone": 2,
    "Low Volatility Contraction": 2,
    "High BTC Correlation": 2,
    "OI Short Covering": 2,
    "London Session": 1,
    "New York Session": 1,
}

WARNING_WEIGHTS = {
    "Opposing CHoCH (active)": (5, "critical"),
    "Market Structure Bearish": (5, "critical"),
    "BOS Bearish Break": (5, "critical"),
    "MTF Strong Bearish": (5, "critical"),
    "Bearish Trend": (5, "critical"),
    "Fake Breakout": (5, "critical"),
    "MACD Bearish Divergence": (4, "critical"),
    "RSI Bearish Divergence": (4, "critical"),
    "Bearish Order Block": (4, "major"),
    "Bearish Trendline Break": (4, "major"),
    "Bearish DI": (4, "major"),
    "Strong Resistance": (3, "major"),
    "Low Volume": (3, "major"),
    "Price Near Resistance": (4, "major"),
    "MTF Bearish": (3, "major"),
    "Bearish Candlestick": (3, "major"),
    "OI Short Build Up": (3, "major"),
    "High Volatility": (3, "minor"),
    "Premium Zone": (2, "minor"),
    "Price Below VWAP": (3, "major"),
    "Sell Side Liquidity Sweep": (3, "major"),
    "Unfilled Bearish FVG": (2, "minor"),
    "OI Long Unwinding": (2, "minor"),
    "Ranging/Choppy": (3, "major"),
    "Funding Bearish Bias": (2, "minor"),
    "Sideways Trend": (2, "minor"),
}

# وزن عوامل تأثیرگذار در Confidence (0 تا 100)
CONFIDENCE_FACTORS = {
    "trend_bullish": 15,
    "trend_bearish": -15,
    "strength_very_strong": 25,
    "strength_strong": 18,
    "strength_medium": 10,
    "strength_weak": -10,
    "mtf_bullish_strong": 15,
    "mtf_bullish": 10,
    "mtf_bearish": -10,
    "mtf_bearish_strong": -15,
    "bos_present": 10,
    "ema_aligned": 5,
    "volume_high": 10,
    "volume_low": -3,
    "breakout_real": 15,
    "regime_trending": 10,
    "regime_ranging": -5,
    "divergence_bullish": 5,
    "divergence_bearish": -5,
    "opposing_choch": -5,
    "high_volatility": -3,
    "oi_long_unwinding": -2,
}
